[project]
name = "ultimate-pc-guide-page"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "monsterui>=1.0.6",
    "python-fasthtml>=0.12.1",
]
